//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB120_05_A3_Vorlage.DB
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Documents;
    using System.Windows.Media.Imaging;

    public partial class Hotel
    {
        string DefaultFilePath = @"C:\Users\vmadmin\Desktop\GUITravel\NotFound.png";
        public virtual BitmapImage BitmapImage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
             this.HotelBild = new HashSet<HotelBild>();
            this.Reise_Hotel = new HashSet<Reise_Hotel>();
            /*
            if (HotelBild.Count >0)
            {
                if ((HotelBild as List<DB.HotelBild>)[0].Bild != null)
                {
                    this.BitmapImage = Program.BitmapImageFromBytes((HotelBild as List<DB.HotelBild>)[0].Bild);

                }  
            }*/
            
           BitmapImage = new BitmapImage(new Uri(DefaultFilePath));
        }

        
        public long     HotelID         { get; set; }
        public string   Name         { get; set; }
        public string   Ort             { get; set; }
        public long     Land         { get; set; }
        public byte     Sterne         { get; set; }
        public string   Manager         { get; set; }
        public short    AnzahlZimmer         { get; set; }
        public decimal  TagesPreis         { get; set; }
        public string   Telefon         { get; set; }
        public string   Email         { get; set; }
        public string   Web             { get; set; }
        public virtual Land Land1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelBild> HotelBild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reise_Hotel> Reise_Hotel { get; set; }
    }
}
