//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB120_05_A3_Vorlage.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Kunde : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kunde()
        {
            this.Kunde_Reise = new HashSet<Kunde_Reise>();
        }

        /*public Kunde(Kunde client)
        {
            KundeID         = client.KundeID;     
            Anrede        = client.Anrede ;
            Vorname       = client.Vorname ;
            Name          = client.Name ;
            NameZusatz    = client.NameZusatz ;
            StrasseNr     = client.StrasseNr ;
            PLZ           = client.PLZ ;
            Ort           = client.Ort ;
            Telefon       = client.Telefon ;
            Mobile        = client.Mobile ;
            Email         = client.Email ;
             Web           = client.Web ;
            PassNr        = client.PassNr ;
            Nationalitaet = client.Nationalitaet ;
        }*/

        public long KundeID { get; set; }
        public string Anrede { get; set; }
        public string Vorname { get; set; }
        public string Name { get; set; }
        public string NameZusatz { get; set; }
        public string StrasseNr { get; set; }
        public short PLZ { get; set; }
        public string Ort { get; set; }
        public string Telefon { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public string PassNr { get; set; }
        public long Nationalitaet { get; set; }

        public virtual Land Land { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kunde_Reise> Kunde_Reise { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;


        public void NotifyPropertyChanged(string propName)
        {
            if (this.PropertyChanged != null)
                this.PropertyChanged(this, new PropertyChangedEventArgs(propName));
        }
    }
}
